name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: bash build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/

      - name: Rename
        run: |
          mv ${{ github.workspace }}/artifact/*.deb ${{ github.workspace }}/artifact/kernel.deb


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 6.7-NightWind
          body_path: RELEASE_CHANGELOG.md
          prerelease: false
          draft: true
          generate_release_notes: true
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/artifact/kernel.deb